version: '3.8'

services:
  api01: &api
    build: .
    hostname: api01
    ports:
      - '8081:8080'
    depends_on:
      db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - '8082:8080'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./config/postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgres.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -U admin -d rinha']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024MB'

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024MB'

networks:
  default:
    driver: bridge
    name: rinha-backend-2024-q1-dotnet
