version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    ports:
      - '5432:5432'

networks:
  default:
    driver: bridge
    name: rinha-backend-2024-q1-dotnet-aot
