version: '3.8'

services:
  api01: &api
    image: samueljansem/rinha-backend-2024-q1-dotnet:latest
    hostname: api01
    ports:
      - '8081:8080'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '20MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - '8082:8080'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./config/postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgres.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '490MB'

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024-q1-dotnet
